version: '2'
services:
    web:
        image: node-image
        env_file:
            - redis_env
        volumes:
            - ./node:/app/
        links:
            - redis
        networks:
            - frontend
            - backend
    redis:
        image: redis-image
        volumes:
            - ./redis:/data
        networks:
            - backend
    lb:
        image: dockercloud/haproxy
        links:
            - web
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 80:80
        networks:
            - frontend
networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
